export const LOAD_USERS_REQUEST = 'users/LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS = 'users/LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'users/LOAD_USERS_FAILURE';

export const LOAD_USER_REQUEST = 'users/LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'users/LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'users/LOAD_USER_FAILURE';